export default {
  domains: [
    'www.starbucks.com',
    'gift.starbucks.co.jp',
    'www.starbucks.co.jp',
    'www.starbucks.com.cn',
    'www.starbucks.de',
    'www.starbucks.fr',
    'www.starbucks.co.uk',
    'www.starbucks.co.uk',
    'www.starbucks.com.br',
    'www.starbucks.ca',
    'card.starbucks.com.sg',
    'www.istarbucks.co.kr',
    'ec.starbucks.com.cn',
    'preview.starbucks.com',
    'app.starbucks.com',
    'login.starbucks.co.jp/login',
    'cart.starbucks.co.jp',
    'www.starbucks.com.sg',
    'www.starbucksreserve.com',
    'www.teavana.com',
  ],
};
